### ISSUE TITLE
KcpStream blocks tokio runtime when the connection closed both physically and abruptly

### ISSUE THREAD

**Issue by Banyc** [Matrix-Zhang/tokio_kcp#29]
# Background

Given that:

```rust
// `a`: KcpStream
// `b`: TimeoutStream<TcpStream>

let (mut a_r, mut a_w) = tokio::io::split(a);
let (mut b_r, mut b_w) = tokio::io::split(b);

let done = tokio::select! {
    res = tokio::io::copy(&mut a_r, &mut b_w) => {
        Done::FromAToB(res.map_err(TimedCopyBiError::FromAToB)?)
    }
    res = tokio::io::copy(&mut b_r, &mut a_w) => {
        Done::FromBToA(res.map_err(TimedCopyBiError::FromBToA)?)
    }
};

let res = match done {
    Done::FromAToB(a_to_b) => (a_to_b, 0),
    Done::FromBToA(b_to_a) => (0, b_to_a),
};
Ok(res)
```

- The `KcpStream` is created by a `KcpListener`.
- The `TcpStream` is connected to the origin server.

The blocking happens when the peer of the `KcpStream` switches off its network connection abruptly.

# Behavior

`netstat -an` shows that there are a few TCP connections that are either stuck in `CLOSE_WAIT` or in `ESTABLISHED` while in both cases the Recv-Q are not zero numbers (but the Send-Qs are all zeros).

`TimeoutStream` will trigger an `io::ErrorKind::Timeout` if the read side remains idle for a whole minute. But it is defied by the aforementioned FDs.

It seems to me that the `KcpStream`s have somehow blocked the tokio runtime.

**Comment by Banyc** [comment]
I have switched `a` to `TimeoutStream<TcpStream>` for comparison. There is no leaked FD in this scenario.

**Comment by Banyc** [comment]
It might not be the problem of KcpStream because I see a possible code branch in `tokio::io::copy` that skips all `poll_read` of the read side. The read timeout only gets triggered once `TimeoutStream::poll_read` is called after the timeout duration.

**Comment by zonyitoo** [comment]
Well, this is because KCP doesn't define something like "keep-alive", or `FIN` to acknowledge the other end has gone. This has to be done in the application level, I believe.

**Comment by Banyc** [comment]
Wrapping `TimeoutStream<KcpStream>` seems to solve the problem. Thank you for maintaining this lib @zonyitoo !
