### ISSUE TITLE
发送和接收函数都是mut self,怎么搞才能多线程同时发送接收呢

### ISSUE THREAD

**Issue by CheemsThx** [Matrix-Zhang/tokio_kcp#40]
发送和接收函数都是mut self,怎么搞才能同时发送接收呢,还是说kcp不支持这个场景了

**Comment by CheemsThx** [comment]
我发现TCP协议接口也是这样的,不知道是不是我写代码的思路有问题,想实现一个线程接收,多个线程发送的,这种方式是否不安全

**Comment by zonyitoo** [comment]
> 多个线程发送的,这种方式是否不安全

是。
