### ISSUE TITLE
When the server restarts, the client freezes

### ISSUE THREAD

**Issue by tkzcfc** [Matrix-Zhang/tokio_kcp#41]
Hello, when using this library, communication between the client and server is very smooth. However, when I restart the server, the client will output an error but will not fail to read or write. When I restart the server again, the client completely dies, but the server will print output and receive a new connection

client code:
```

#[tokio::main]
async fn main() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("debug")).init();

    let config = KcpConfig::default();

    let server_addr = "127.0.0.1:3100".parse::<SocketAddr>().unwrap();

    let mut stream = KcpStream::connect(&config, server_addr).await.unwrap();

    let mut count: u128 = 0;
    loop {
        count += 1;
        stream.write_u128(count).await.unwrap();

        let value = stream.read_u128().await.unwrap();
        println!("count: {}", value);
    }
}


```

server code:

```


#[tokio::main]
async fn main() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("debug")).init();


    let config = KcpConfig::default();

    let server_addr = "0.0.0.0:3100".parse::<SocketAddr>().unwrap();

    let mut listener = KcpListener::bind(config, server_addr).await.unwrap();

    loop {
        let (mut stream, peer_addr) = match listener.accept().await {
            Ok(s) => s,
            Err(err) => {
                error!("accept failed, error: {}", err);
                time::sleep(Duration::from_secs(1)).await;
                continue;
            }
        };

        info!("accepted {}", peer_addr);

        tokio::spawn(async move {
            let mut buffer = [0u8; 8192];
            while let Ok(n) = stream.read(&mut buffer).await {
                debug!("recv {:?}", ByteStr::new(&buffer[..n]));
                if n == 0 {
                    break;
                }
                stream.write_all(&buffer[..n]).await.unwrap();
                debug!("echo {:?}", ByteStr::new(&buffer[..n]));
            }

            debug!("client {} closed", peer_addr);
        });
    }
}

```

**Comment by zonyitoo** [comment]
KCP are running on UDP protocol, so your clients didn't know servers were gone when you restarted the server process.

**Comment by tkzcfc** [comment]
So, in practical use, I need to add a ping message to detect whether I am alive on my own?

**Comment by tkzcfc** [comment]
Can the KCP client continue to connect to the new server and communicate?

**Comment by zonyitoo** [comment]
There is no way for `KcpStream` to "know" whether server is gone, so what it can only do is continue sending packets to the server's IP:Port.

Just like TCP streams, if server is dead completely without sending RST or FIN to clients, client may also block forever.

One suggestion is that you should add timeout wrappers to close sessions that didn't respond in time.

**Comment by tkzcfc** [comment]
It is not easy to detect whether the connection is alive. If my device has no network, I can only know after the timeout (if the timeout is set too long, the experience will be very poor. If it is set too short, the large message has not been completely sent, and the timeout will be triggered. It may just be that my bandwidth is relatively low)
When there is no network or the other party has closed it, udp read/write can get an error. Can it throw an error for KcpStream's read/write at this time?

**Comment by zonyitoo** [comment]
If no route was available, `send` or `recv` should return error because the underlying `KcpSession` is dead.

There is no way to know whether your server have been closed, so no error could be generated.

**Comment by tkzcfc** [comment]
The client output this error, but the session did not handle it

https://github.com/Matrix-Zhang/tokio_kcp/blob/2f303fd73fdf0b6b3bb55a380a3cf3251883dca4/src/session.rs#L104

**Comment by tkzcfc** [comment]
Maybe we should handle this error?

**Comment by zonyitoo** [comment]
Append the following lines:

```rust
session.closed.store(true, Ordering::Release);
break;
```

right after the `error!` log, and see if it works in your case.

**Comment by tkzcfc** [comment]
It solved my problem

**Comment by zonyitoo** [comment]
Please consider make a PR.

**Comment by tkzcfc** [comment]
Submitted 🙂
